### ISSUE TITLE
Texture Locations

### ISSUE THREAD

**Issue by SirSwish** [PieroZ/UrbanChaosUtils#1]
Hi Pieroz, thank you for your efforts with PRIM Visualizer. I want to try to re-implement in C# with helix-Toolkit viewer. Only problem is I don't know which .TXC file contains .TEX textures for Prims. I will incorporate TXC and TEX conversion directly in the App, but how do we know which file contains them?

**Comment by PieroZ** [comment]
I'm not the original author of this conversion tool and I'm away from my PC for several days so I'm afraid I cannot provide you detailed answer for your question, as I would need to study .TXC files to figure it out. 

Try asking your question here https://github.com/Fire-Head/UCTxcTools.

I grabbed extracted organized textures in server directory from here 
https://web.archive.org/web/20231015155917/https://forum.xentax.com/viewtopic.php?f=32&t=16234
so I did not have to study which .TXC file contains which .TEX texture.

**Comment by SirSwish** [comment]
Ah, okay that is no problem, I have done the analysis now so I will self close and for reference I have attached the mapping. Strangely, even after extracting all TXC's from clumps, there were still 3 Prim Textures that were (at least not in their exact form) extracted directly from TXC. But they were relatively simple textures so can easily be recreated anyway.
[Prim Texture Map.txt](https://github.com/PieroZ/UrbanChaosUtils/files/13683829/Prim.Texture.Map.txt)
